name: native_page_view_controller
description: Flutter page curl.
version: 0.0.1
author: River2202 <river2202@gmail.com>
homepage: https://github.com/river2202

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: info.goldenriver.native_page_view_controller
    pluginClass: NativePageViewControllerPlugin
